### ISSUE TITLE
How to install iree-jax

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree-jax#47]
I didn't find a document. 

The notebook https://github.com/iree-org/iree-jax/blob/main/colab/conways_game_of_life.ipynb contains a pip install command. Unfortunately, running it on macOS/arm64 13.1 with Python 3.10 gave me the following errors.

```
11:35 $ pip install git+https://github.com/iree-org/iree-jax
Looking in indexes: https://pypi.apple.com/simple
Collecting git+https://github.com/iree-org/iree-jax
  Cloning https://github.com/iree-org/iree-jax to /private/var/folders/hd/6q8jftdn7b1fygsrzdkp5ww40000gn/T/pip-req-build-uai2j2j8
  Running command git clone --filter=blob:none --quiet https://github.com/iree-org/iree-jax /private/var/folders/hd/6q8jftdn7b1fygsrzdkp5ww40000gn/T/pip-req-build-uai2j2j8
  Resolved https://github.com/iree-org/iree-jax to commit fa3e3d9c06b13f7e8d89749b5c598be49d5e6c9e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /Users/y/miniforge3/envs/iree-jax/lib/python3.10/site-packages (from iree-jax==0.1.dev1) (1.24.1)
Collecting jax>=0.4.1
  Downloading https://pypi.apple.com/packages/packages/c9/cd/5d77845520ea6f3c96b6121ddba7068f9f1b789f4a534005a29cce829804/jax-0.4.2.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement iree-compiler>=20221121.334 (from iree-jax) (from versions: 20220523.147, 20220714.204, 20220811.232, 20220902.254, 20220930.282)
ERROR: No matching distribution found for iree-compiler>=20221121.334
```

**Comment by wangkuiyi** [comment]
`python setup.py develop` failed with the same error -- iree-compiler from pip seems too old. https://github.com/iree-org/iree-jax/issues/46

**Comment by ScottTodd** [comment]
Can you try running this script? https://github.com/iree-org/iree-jax/blob/main/build_tools/pip_install.py (from the iree-jax/ repo root), as here: https://github.com/iree-org/iree-jax/blob/fa3e3d9c06b13f7e8d89749b5c598be49d5e6c9e/.github/workflows/test_gpt2_model.yaml#L25-L28

(Sorry, we're still stabilizing all these releases / published packages)

**Comment by ScottTodd** [comment]
Here's what I think is happening:
The pinned versions in https://github.com/iree-org/iree-jax/blob/main/version_info.json can include nightly releases of the IREE packages that are not published to pypi. The pip_install script and some other samples set `-f https://iree-org.github.io/iree/pip-release-links.html` to include the extra index (see https://pip.pypa.io/en/stable/cli/pip_install/).

The notebook you linked also fails in Colab with the same error: https://colab.research.google.com/github/iree-org/iree-jax/blob/main/colab/conways_game_of_life.ipynb (connect to a hosted runtime and try running the first cell)

So probably not macOS specific.

**Comment by wangkuiyi** [comment]
Thanks @ScottTodd !

Because iree-jax is under development, I tried to install it from source code.

1. Install jax with `pip install jax`
1. Install `iree.compiler` and `iree.runtime` and `iree.jax` by setting the `PYTHONPATH` environment variable.
   ```
   source build/compiler/.env && export PYTHONPATH
   export PYTHONPATH=$PYTHONPATH:$PWD/iree-jax
   ```

And it works.
