### ISSUE TITLE
How to enable iree-compiler, iree-runtime as iree building from source.

### ISSUE THREAD

**Issue by redbopo** [iree-org/iree-jax#70]
Hello!
Following the build from source in [iree-python-bindings](https://openxla.github.io/iree/building-from-source/getting-started/#using-the-python-bindings) .
And it success in 
```
python -c "import iree.compiler"
python -c "import iree.runtime"
```
Coming to install iree-jax from source, it requires the package iree-compiler, iree-runtime.
I think these above two library (eg. iree.compiler to iree-compiler) are almost same except the module name (correct me if i'm wrong).
During `pip install -e .` will download iree_compiler-xxx.whl,

How can I use the local iree build python library? Since I'd like to code with iree .

I also see the common routine when iree dealing with tensorflow and pytorch Integration, IREE package can be installed from pip or 
building from souce, although in fact the [building from souce linkage is broken](https://openxla.github.io/iree/getting-started/tensorflow/) .

**Comment by ScottTodd** [comment]
> although in fact the [building from souce linkage is broken](https://openxla.github.io/iree/getting-started/tensorflow/) .

Argh. Thanks for noticing. Fixing in https://github.com/openxla/iree/pull/13643

**Comment by ScottTodd** [comment]
> How can I use the local iree build python library? Since I'd like to code with iree .

See https://github.com/iree-org/iree-jax/tree/main#using-an-iree-development-tree

(Seems that all you need to do is set up your `PYTHONPATH`, without already having the `.whl` packages installed from pip)

**Comment by ScottTodd** [comment]
`-DIREE_BUILD_LEGACY_JAX=OFF` was removed in https://github.com/openxla/iree/pull/8031... that should no longer be needed anywhere (someone should update the docs in this repo)

---

I'd need to see more repro steps for what you're trying to offer concrete suggestions... I think the local dev steps don't want you running any `pip` commands at all (so https://github.com/iree-org/iree-jax/blob/main/setup.py doesn't get involved and look into the version_info.json file)

**Comment by jpienaar** [comment]
Sounds all good and I'll send a PR to review the legacy comment from readme.
